### ISSUE TITLE
HttpClientService无法引入使用

### ISSUE THREAD

**Issue by zzzhan** [myopenresources/cc#24]
把`LoginComponent`的`HttpService`替换为`HttpClientService`时没有报错，但登录页出不来。去掉`constructor`中`HttpClientService`的引用就可以。不知哪出了问题？ @myopenresources

**Comment by myopenresources** [comment]
@zzzhan http与http-client机制不一样，你得把原来所有用到HttpClientService请求的地方全部修改成HttpClientService

**Comment by zzzhan** [comment]
http-client使用有什么前提吗？跟http的使用有什么不同？我不是升级哦，第一次clone了你的项目，在LoginComponent里只是简单地试一下用http-client.结果页面刷新后是空白的，也没报什么错。 @myopenresources

**Comment by zzzhan** [comment]
找到问题了，需要在`app.module.ts`里把`HttpModule`替换为`HttpClientModule`,`HttpService`替换为`HttpClientService`. Work like a charm:)

**Comment by myopenresources** [comment]
@zzzhan 恩，是的
